# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/pi/My Documents/OF0071_ARM/OF0071_ARM/LIBS/poco-1.4.3p1
POCO_BUILD = /home/pi/My Documents/OF0071_ARM/OF0071_ARM/LIBS/poco-1.4.3p1
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = 
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
.PHONY: poco
poco: libexecs tests samples
